# Generated by Django 5.2.17 on 2026-09-12 11:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('junior_high', 'Junior High School'), ('senior_high', 'Senior High School'), ('university', 'Undergraduate Student')], default='university', max_length=20)),
                ('logo', models.CharField(blank=True, help_text='Nama file logo di static/img/, contoh: ui-logo.svg', max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
