# Generated by Django 5.2.17 on 2026-09-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['started_at']},
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, help_text='Cerita singkat atau pencapaian selama di institusi ini', null=True),
        ),
    ]
