# Generated by Django 5.2.17 on 2026-09-15 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tech_stack',
            new_name='skills_used',
        ),
    ]
