# Generated by Django 5.2.17 on 2026-09-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_tech_stack_project_skills_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-started_at']},
        ),
    ]
