# Generated by Django 5.2.17 on 2026-09-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_education_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='logo',
            field=models.URLField(blank=True, help_text='URL logo institusi', max_length=500, null=True),
        ),
    ]
