# Generated by Django 5.2.17 on 2026-09-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_education_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='URL gambar pengalaman', max_length=500, null=True),
        ),
    ]
